/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/api/v1/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare two completed runs */
        get: operations["compare_api_v1_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List runs (newest first) */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        /** Create and queue a run */
        post: operations["create_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List artifacts */
        get: operations["artifacts_api_v1_runs__run_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/artifacts/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download an artifact */
        get: operations["artifact_api_v1_runs__run_id__artifacts__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a run */
        post: operations["cancel_api_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run events */
        get: operations["events_api_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics and score */
        get: operations["metrics_api_v1_runs__run_id__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/recording": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Replay recording (normalized telemetry and events) */
        get: operations["recording_api_v1_runs__run_id__recording_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Canonical JSON report */
        get: operations["report_api_v1_runs__run_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/report.html": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Standalone HTML report */
        get: operations["report_html_api_v1_runs__run_id__report_html_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run telemetry */
        get: operations["telemetry_api_v1_runs__run_id__telemetry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the scenario library */
        get: operations["list_scenarios_api_v1_scenarios_get"];
        put?: never;
        /** Create or update a scenario in the library */
        post: operations["create_scenario_api_v1_scenarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a scenario */
        get: operations["get_scenario_api_v1_scenarios__name__get"];
        put?: never;
        post?: never;
        /** Delete a user scenario */
        delete: operations["delete_scenario_api_v1_scenarios__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{name}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the raw YAML document */
        get: operations["get_scenario_document_api_v1_scenarios__name__document_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate a scenario document */
        post: operations["validate_scenario_api_v1_scenarios_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Platform, topology and catalog */
        get: operations["system_info_api_v1_system_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe (database, bus, artifact store) */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** AdapterOut */
        AdapterOut: {
            /** Data Origin */
            data_origin: string;
            /** Description */
            description: string;
            /** Display Name */
            display_name: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Online */
            online: boolean;
            /**
             * Requirements
             * @default
             */
            requirements: string;
            /** Runners */
            runners: string[];
            status: components["schemas"]["AdapterStatus"];
        };
        /**
         * AdapterStatus
         * @enum {string}
         */
        AdapterStatus: "available" | "experimental" | "planned";
        /** ApiError */
        ApiError: {
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Error */
            error: string;
            /** Issues */
            issues?: components["schemas"]["ValidationIssue"][];
        };
        /** ArtifactOut */
        ArtifactOut: {
            /** Content Type */
            content_type: string;
            /** Description */
            description: string;
            /** Name */
            name: string;
            /** Sha256 */
            sha256: string | null;
            /** Size Bytes */
            size_bytes: number;
            /** Url */
            url: string;
        };
        /** AssertionComparison */
        AssertionComparison: {
            /** Baseline */
            baseline: string | null;
            /** Candidate */
            candidate: string | null;
            /** Expression */
            expression: string;
            /** Severity */
            severity: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "improvement" | "regression" | "unchanged" | "changed" | "not_comparable";
        };
        /**
         * AssertionOutcome
         * @enum {string}
         */
        AssertionOutcome: "passed" | "failed" | "not_evaluated";
        /** AssertionResult */
        AssertionResult: {
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Expected
             * @description Literal the metric was compared against
             */
            expected: number | boolean;
            /** Explanation */
            explanation: string;
            /** Expression */
            expression: string;
            /**
             * Measured
             * @description Value observed for the metric path
             */
            measured: number | boolean | null;
            /** Metric Path */
            metric_path: string;
            /** Operator */
            operator: string;
            outcome: components["schemas"]["AssertionOutcome"];
            severity: components["schemas"]["Severity"];
            /**
             * Simulation Time
             * @description Simulation time at which the metric was finalized
             */
            simulation_time?: number | null;
        };
        /** Attitude */
        Attitude: {
            /**
             * Pitch
             * @description Pitch angle (rad)
             */
            pitch: number;
            /**
             * Roll
             * @description Roll angle (rad)
             */
            roll: number;
            /**
             * Yaw
             * @description Yaw / heading angle (rad, 0 = north, clockwise positive)
             */
            yaw: number;
        };
        /**
         * AvailabilityMetrics
         * @description Fraction of run time during which a domain delivered its function.
         */
        AvailabilityMetrics: {
            /** Communications */
            communications: number;
            /** Compute */
            compute: number;
            /** Control */
            control: number;
            /** Navigation */
            navigation: number;
            /**
             * Navigation Integrity
             * @description Weighted: healthy 1.0, degraded 0.5, down 0.0
             */
            navigation_integrity: number;
            /** Power */
            power: number;
        };
        /**
         * BenchmarkResult
         * @description Outcome of a run once analyzed.
         *
         *     `passed` and `failed` are only emitted for runs that completed their scenario.
         *     `inconclusive` marks runs that could not be fully executed or analyzed.
         * @enum {string}
         */
        BenchmarkResult: "passed" | "failed" | "inconclusive";
        /** CancelResponse */
        CancelResponse: {
            /** Delivered */
            delivered: boolean;
            run: components["schemas"]["RunSummary"];
        };
        /** CatalogEntryOut */
        CatalogEntryOut: {
            /** Category */
            category: string;
            /** Critical */
            critical: boolean;
            /** Description */
            description: string;
            /** Domain */
            domain: string;
            /** Effects */
            effects: components["schemas"]["Effect"][];
            healthy_state: components["schemas"]["ComponentState"];
            /** Name */
            name: string;
            /** Subsystem */
            subsystem: string;
            /** Trust Zone */
            trust_zone: string;
        };
        /** CommunicationsStatus */
        CommunicationsStatus: {
            /** C2 Link */
            c2_link: boolean;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Packet Loss */
            packet_loss?: number | null;
            /** Telemetry Link */
            telemetry_link: boolean;
        };
        /** CompareResponse */
        CompareResponse: {
            /** Assertions */
            assertions: components["schemas"]["AssertionComparison"][];
            baseline: components["schemas"]["RunSummary"];
            /** Baseline Events */
            baseline_events: components["schemas"]["RunEvent"][];
            candidate: components["schemas"]["RunSummary"];
            /** Candidate Events */
            candidate_events: components["schemas"]["RunEvent"][];
            /** Dimensions */
            dimensions: components["schemas"]["DimensionComparison"][];
            /** Improvements */
            improvements: number;
            /** Metrics */
            metrics: components["schemas"]["MetricComparison"][];
            /** Regressions */
            regressions: number;
            /** Same Scenario */
            same_scenario: boolean;
            /** Same Scenario Hash */
            same_scenario_hash: boolean;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "regression" | "improvement" | "unchanged" | "mixed" | "not_comparable";
        };
        /** Component */
        Component: {
            category: components["schemas"]["FaultCategory"];
            /**
             * Critical
             * @description Loss of this component means loss of flight-critical function
             * @default false
             */
            critical: boolean;
            /**
             * Description
             * @default
             */
            description: string;
            domain: components["schemas"]["Domain"];
            /**
             * @description Vocabulary used when the component is healthy (NOMINAL or OPERATIONAL)
             * @default NOMINAL
             */
            healthy_state: components["schemas"]["ComponentState"];
            /**
             * Id
             * @description Subsystem identifier '<category>.<component>'
             */
            id: string;
            /** Name */
            name: string;
            trust_zone: components["schemas"]["TrustZone"];
        };
        /** ComponentHealth */
        ComponentHealth: {
            /** Artifact Store */
            artifact_store: boolean;
            /** Bus */
            bus: boolean;
            /** Database */
            database: boolean;
        };
        /**
         * ComponentState
         * @description Observed operating state of a system component or subsystem.
         *
         *     Semantics:
         *
         *     - `NOMINAL`: performing within specification, no active fault. Used for sensors,
         *       navigation, communications and power components.
         *     - `OPERATIONAL`: performing its function. Used for flight control, actuation and
         *       compute components where "operational" is the natural vocabulary. Equivalent to
         *       `NOMINAL` for every calculation.
         *     - `DEGRADED`: still performing its function with reduced quality, capacity or
         *       confidence (for example navigation without GNSS aiding).
         *     - `UNAVAILABLE`: the function is not being provided (link lost, sensor silent) but
         *       the component itself did not fail.
         *     - `FAILED`: the component itself failed (crash, fault latch, loss of control).
         *     - `RECOVERING`: a recovery action is in progress (process restart, re-acquisition).
         *     - `RECOVERED`: back to a healthy state after a fault. Behaves as healthy for every
         *       availability calculation; kept distinct so timelines show the recovery.
         *     - `UNKNOWN`: no observation is available for this component.
         * @enum {string}
         */
        ComponentState: "NOMINAL" | "OPERATIONAL" | "DEGRADED" | "UNAVAILABLE" | "FAILED" | "RECOVERING" | "RECOVERED" | "UNKNOWN";
        /** ComponentStateInterval */
        ComponentStateInterval: {
            /** End */
            end: number;
            /** Start */
            start: number;
            state: components["schemas"]["ComponentState"];
            /** Subsystem */
            subsystem: string;
        };
        /**
         * Dependency
         * @description `dependent` relies on `provider`; a fault on the provider may propagate downstream.
         */
        Dependency: {
            /**
             * Crosses Trust Boundary
             * @default false
             */
            crosses_trust_boundary: boolean;
            /** Dependent */
            dependent: string;
            /** Provider */
            provider: string;
            /**
             * Relation
             * @default depends_on
             */
            relation: string;
        };
        /** DimensionComparison */
        DimensionComparison: {
            /** Baseline */
            baseline: number | null;
            /** Candidate */
            candidate: number | null;
            /** Delta */
            delta: number | null;
            /** Dimension */
            dimension: string;
            /** Label */
            label: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "improvement" | "regression" | "unchanged" | "not_comparable";
            /** Weight */
            weight: number;
        };
        /** DimensionScore */
        DimensionScore: {
            /** Dimension */
            dimension: string;
            /** Explanation */
            explanation: string;
            /** Label */
            label: string;
            /**
             * Points
             * @description score * weight
             */
            points: number;
            /**
             * Score
             * @description Normalized dimension score
             */
            score: number;
            /** Weight */
            weight: number;
        };
        /**
         * Domain
         * @enum {string}
         */
        Domain: "external" | "communications" | "navigation" | "mission_compute" | "flight_control" | "actuation" | "power";
        /**
         * Effect
         * @enum {string}
         */
        Effect: "unavailable" | "intermittent" | "degraded" | "erroneous" | "stuck" | "restart" | "crash" | "latency" | "packet_loss" | "resource_pressure" | "temporary_disconnect";
        /** EffectDescriptor */
        EffectDescriptor: {
            /** Description */
            description: string;
            /** Duration Required */
            duration_required: boolean;
            effect: components["schemas"]["Effect"];
            /** Parameters */
            parameters: components["schemas"]["ParameterSpecOut"][];
            /** Transient */
            transient: boolean;
        };
        /** EventCounts */
        EventCounts: {
            /** Applied */
            applied: number;
            /** Cleared */
            cleared: number;
            /** Degraded Transitions */
            degraded_transitions: number;
            /** Expectations Failed */
            expectations_failed: number;
            /** Expectations Passed */
            expectations_passed: number;
            /** Failed Transitions */
            failed_transitions: number;
            /** Injected */
            injected: number;
            /** Observed Effects */
            observed_effects: number;
            /** Recoveries */
            recoveries: number;
            /** Rejected */
            rejected: number;
            /** System Responses */
            system_responses: number;
        };
        /**
         * EventKind
         * @description Scientific classification of a run event.
         *
         *     The distinction matters: a requested disturbance is not evidence that the
         *     system was actually disturbed, and an expected response is not evidence that
         *     it happened.
         *
         *     - `INJECTION_REQUEST`: the scenario engine asked the adapter to inject an effect.
         *     - `INJECTION_APPLIED`: the adapter confirmed the effect is active in the target.
         *     - `INJECTION_REJECTED`: the adapter could not apply the effect.
         *     - `INJECTION_CLEARED`: the effect was removed (duration elapsed or scenario end).
         *     - `OBSERVED_EFFECT`: a component state change observed in the target.
         *     - `SYSTEM_RESPONSE`: an autonomous reaction of the target (mode change, failsafe).
         *     - `RECOVERY`: a component returned to a healthy state.
         *     - `EXPECTATION_RESULT`: an expected behaviour declared in the scenario was checked.
         *     - `ASSERTION_RESULT`: a scenario assertion was evaluated during analysis.
         *     - `MISSION`: mission progress (waypoint reached, mission complete).
         *     - `LIFECYCLE`: run lifecycle transition.
         *     - `LOG`: informational message from a component.
         * @enum {string}
         */
        EventKind: "INJECTION_REQUEST" | "INJECTION_APPLIED" | "INJECTION_REJECTED" | "INJECTION_CLEARED" | "OBSERVED_EFFECT" | "SYSTEM_RESPONSE" | "RECOVERY" | "EXPECTATION_RESULT" | "ASSERTION_RESULT" | "MISSION" | "LIFECYCLE" | "LOG";
        /** EventMessage */
        EventMessage: {
            event: components["schemas"]["RunEvent"];
            /**
             * Protocol Version
             * @default 1
             */
            protocol_version: string;
            /** Run Id */
            run_id: string;
            /**
             * Sent At
             * Format: date-time
             */
            sent_at?: string;
            /**
             * Type
             * @default event
             * @constant
             */
            type: "event";
        };
        /**
         * EventSource
         * @enum {string}
         */
        EventSource: "scenario" | "adapter" | "engine" | "analysis" | "platform";
        /** EventsResponse */
        EventsResponse: {
            /** Count */
            count: number;
            /** Events */
            events: components["schemas"]["RunEvent"][];
            /** Next After Sequence */
            next_after_sequence: number | null;
            /** Run Id */
            run_id: string;
        };
        /**
         * FaultCategory
         * @description Fault library categories exposed to scenario authors.
         * @enum {string}
         */
        FaultCategory: "Navigation" | "Sensors" | "Communications" | "Compute" | "Process" | "Network" | "Power" | "Security boundary" | "Service";
        /**
         * FlightMode
         * @description Vehicle-level operating mode reported by the adapter.
         * @enum {string}
         */
        FlightMode: "IDLE" | "TAKEOFF" | "MISSION" | "HOLD" | "RTL" | "LAND" | "LANDED" | "UNKNOWN";
        /** FlightStatus */
        FlightStatus: {
            /** Armed */
            armed: boolean;
            /**
             * Autonomy
             * @description Which entity is currently driving the vehicle: mission, local, failsafe
             * @default mission
             */
            autonomy: string;
            /**
             * Control Authority
             * @description True while the flight core has full control of the vehicle
             */
            control_authority: boolean;
            mode: components["schemas"]["FlightMode"];
        };
        /** GeoPosition */
        GeoPosition: {
            /**
             * Altitude Msl
             * @description Altitude above mean sea level (m)
             */
            altitude_msl: number;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /** HardGate */
        HardGate: {
            /** Name */
            name: string;
            /** Passed */
            passed: boolean;
            /** Reason */
            reason: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LifecycleMessage */
        LifecycleMessage: {
            /**
             * Adapter Version
             * @default null
             */
            adapter_version: string | null;
            /**
             * Data Origin
             * @default null
             */
            data_origin: string | null;
            /** @default null */
            planned_path: components["schemas"]["PlannedPath"] | null;
            /** @default null */
            previous_state: components["schemas"]["RunState"] | null;
            /**
             * Protocol Version
             * @default 1
             */
            protocol_version: string;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Run Id */
            run_id: string;
            /** Runner Id */
            runner_id: string;
            /**
             * Sent At
             * Format: date-time
             */
            sent_at?: string;
            /**
             * Simulation Time
             * @default 0
             */
            simulation_time: number;
            state: components["schemas"]["RunState"];
            /**
             * Type
             * @default lifecycle
             * @constant
             */
            type: "lifecycle";
        };
        /** MetricComparison */
        MetricComparison: {
            /** Baseline */
            baseline: number | boolean | null;
            /**
             * Better
             * @enum {string}
             */
            better: "higher" | "lower" | "neutral";
            /** Candidate */
            candidate: number | boolean | null;
            /** Delta */
            delta: number | null;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * Unit
             * @enum {string}
             */
            unit: "percent" | "seconds" | "count" | "score" | "bool";
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "improvement" | "regression" | "unchanged" | "changed" | "not_comparable";
        };
        /** MetricsResponse */
        MetricsResponse: {
            /** Assertions */
            assertions: components["schemas"]["AssertionResult"][];
            /** Context */
            context: {
                [key: string]: number | boolean | null;
            };
            metrics: components["schemas"]["MetricsResult"];
            /** Run Id */
            run_id: string;
            score: components["schemas"]["ScoreResult"];
        };
        /** MetricsResult */
        MetricsResult: {
            availability: components["schemas"]["AvailabilityMetrics"];
            /** Component Time In State */
            component_time_in_state: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            events: components["schemas"]["EventCounts"];
            /** Final Component States */
            final_component_states: {
                [key: string]: components["schemas"]["ComponentState"];
            };
            mission: components["schemas"]["MissionMetrics"];
            modes: components["schemas"]["ModeMetrics"];
            propagation: components["schemas"]["PropagationMetrics"];
            recovery: components["schemas"]["RecoveryMetrics"];
            /** Run Duration */
            run_duration: number;
            safety: components["schemas"]["SafetyMetrics"];
            /** Sample Count */
            sample_count: number;
        };
        /** MissionMetrics */
        MissionMetrics: {
            /** Completed */
            completed: boolean;
            /**
             * Completion
             * @description Fraction of mission objectives reached
             */
            completion: number;
            /**
             * Continuity
             * @description 1 - (time held or diverted / duration)
             */
            continuity: number;
            /**
             * Duration
             * @description Simulation seconds from start to end of run
             */
            duration: number;
            /** Time In Hold */
            time_in_hold: number;
            /** Time In Mission Modes */
            time_in_mission_modes: number;
        };
        /**
         * MissionPhase
         * @enum {string}
         */
        MissionPhase: "PENDING" | "TAKEOFF" | "ENROUTE" | "HOLDING" | "RETURNING" | "LANDING" | "COMPLETE" | "ABORTED";
        /** MissionStatus */
        MissionStatus: {
            /**
             * Distance To Waypoint
             * @description Metres
             */
            distance_to_waypoint?: number | null;
            phase: components["schemas"]["MissionPhase"];
            /**
             * Progress
             * @description Mission completion ratio
             */
            progress: number;
            /**
             * Waypoint Index
             * @description Index of the waypoint currently targeted
             */
            waypoint_index: number;
            /** Waypoints Total */
            waypoints_total: number;
        };
        /** ModeMetrics */
        ModeMetrics: {
            /** Time Degraded */
            time_degraded: number;
            /** Time Failed */
            time_failed: number;
            /** Time Nominal */
            time_nominal: number;
            /** Total */
            total: number;
        };
        /** NavigationStatus */
        NavigationStatus: {
            /** Gnss Fix */
            gnss_fix: boolean;
            /**
             * Position Error
             * @description Estimated horizontal position error (m)
             */
            position_error: number;
            /** Satellites */
            satellites?: number | null;
            /**
             * Source
             * @description Position source: gnss, dead_reckoning, none
             */
            source: string;
        };
        /** ParameterSpecOut */
        ParameterSpecOut: {
            /** Description */
            description: string;
            /** Maximum */
            maximum?: number | null;
            /** Minimum */
            minimum?: number | null;
            /** Name */
            name: string;
            /** Type */
            type: string;
        };
        /** PathPoint */
        PathPoint: {
            /** T */
            t: number;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z: number;
        };
        /**
         * PlannedPath
         * @description Mission plan as known before the run: waypoints in the local ENU frame.
         */
        PlannedPath: {
            origin?: components["schemas"]["GeoPosition"] | null;
            /** @description Return / safe landing point */
            safe_zone?: components["schemas"]["Position"] | null;
            /**
             * Safe Zone Radius
             * @default 15
             */
            safe_zone_radius: number;
            /** Waypoints */
            waypoints: components["schemas"]["Position"][];
        };
        /**
         * Position
         * @description Local position in an East-North-Up frame relative to the mission origin (metres).
         */
        Position: {
            /**
             * X
             * @description East (m)
             */
            x: number;
            /**
             * Y
             * @description North (m)
             */
            y: number;
            /**
             * Z
             * @description Up, altitude above origin (m)
             */
            z: number;
        };
        /** PowerStatus */
        PowerStatus: {
            /** Current */
            current?: number | null;
            /** Remaining */
            remaining: number;
            /** Voltage */
            voltage: number;
        };
        /** PropagationMetrics */
        PropagationMetrics: {
            /** Affected Components */
            affected_components: string[];
            /** Affected Domains */
            affected_domains: components["schemas"]["Domain"][];
            /**
             * Boundary Crossed
             * @description A trust boundary was crossed by the propagation
             */
            boundary_crossed: boolean;
            /** Contained */
            contained: boolean;
            /** Critical Domain Reached */
            critical_domain_reached: boolean;
            /** Depths */
            depths: {
                [key: string]: number;
            };
            /** Flight Domain Affected */
            flight_domain_affected: boolean;
            /** Injected Components */
            injected_components: string[];
            /** Injected Domains */
            injected_domains: components["schemas"]["Domain"][];
            /** Max Propagation Depth */
            max_propagation_depth: number;
            /**
             * Propagated Components
             * @description Affected components that were not injection targets
             */
            propagated_components: string[];
            /** Propagated Domains */
            propagated_domains: components["schemas"]["Domain"][];
            /** Propagation Count */
            propagation_count: number;
        };
        /** Provenance */
        Provenance: {
            /** Adapter */
            adapter: string;
            /** Adapter Version */
            adapter_version?: string | null;
            /**
             * Data Origin
             * @description simulation, replay or hardware-in-the-loop
             * @default simulation
             */
            data_origin: string;
            /** Ended At */
            ended_at?: string | null;
            /**
             * Environment
             * @description Non-sensitive environment metadata (platform, python)
             */
            environment?: {
                [key: string]: string;
            };
            /**
             * Git Commit
             * @description Git SHA of the platform build
             */
            git_commit?: string | null;
            /** Image Versions */
            image_versions?: {
                [key: string]: string;
            };
            /**
             * Protocol Version
             * @default 1
             */
            protocol_version: string;
            /** Runner Id */
            runner_id?: string | null;
            /**
             * Scenario Api Version
             * @default resilient-uas.dev/v1alpha1
             */
            scenario_api_version: string;
            /**
             * Scenario Hash
             * @description sha256 of the canonical scenario document
             */
            scenario_hash: string;
            /** Scenario Version */
            scenario_version: string;
            /**
             * Score Profile
             * @default default
             */
            score_profile: string;
            /** Seed */
            seed: number;
            /**
             * Software Version
             * @default 0.1.0
             */
            software_version: string;
            /** Speed */
            speed: number;
            /** Started At */
            started_at?: string | null;
            /** Target Configuration */
            target_configuration?: {
                [key: string]: string | number | boolean;
            };
        };
        /**
         * RecordingOut
         * @description Normalized recording of a run, consumable by the replay adapter.
         */
        RecordingOut: {
            /** Events */
            events: components["schemas"]["RunEvent"][];
            /**
             * Format Version
             * @constant
             */
            format_version: "1";
            planned_path: components["schemas"]["PlannedPath"] | null;
            /** Samples */
            samples: components["schemas"]["TelemetrySample"][];
            /** Scenario Name */
            scenario_name: string;
            /** Source Adapter */
            source_adapter: string;
            /** Source Run Id */
            source_run_id: string;
        };
        /** RecoveryMetrics */
        RecoveryMetrics: {
            /** Faults Recovered */
            faults_recovered: number;
            /** Faults Requiring Recovery */
            faults_requiring_recovery: number;
            /** Max Time To Recovery */
            max_time_to_recovery: number | null;
            /**
             * Mean Time To Recovery
             * @description Seconds; None when nothing recovered
             */
            mean_time_to_recovery: number | null;
            /**
             * Per Subsystem Max
             * @description Maximum recovery time per subsystem (seconds)
             */
            per_subsystem_max: {
                [key: string]: number;
            };
            /** Records */
            records: components["schemas"]["RecoveryRecord"][];
            /** Safe State Entered */
            safe_state_entered: boolean;
            /**
             * Success Rate
             * @description recovered / requiring; None when none required
             */
            success_rate: number | null;
            /**
             * Time To Safe State
             * @description Seconds from the observed fault that triggered the first safe-state response to that response
             */
            time_to_safe_state: number | null;
        };
        /** RecoveryRecord */
        RecoveryRecord: {
            /**
             * Caused By
             * @description Scenario event id when attributable
             */
            caused_by: string | null;
            /**
             * Direct
             * @description True when the fault is the injected subsystem itself
             */
            direct: boolean;
            /**
             * Disturbance Cleared At
             * @description When the causing injection was cleared, if bounded
             */
            disturbance_cleared_at?: number | null;
            /**
             * Fault Duration
             * @description Seconds from fault start to recovery
             */
            fault_duration: number | null;
            /** Fault Started At */
            fault_started_at: number;
            fault_state: components["schemas"]["ComponentState"];
            /** Recovered At */
            recovered_at: number | null;
            /**
             * Recovery Expected
             * @description False when the injected effect persisted until scenario end
             */
            recovery_expected: boolean;
            /**
             * Recovery Time
             * @description Seconds needed to recover once the disturbance ended: measured from the moment the causing injection was cleared (or from fault start for transient and self-inflicted faults) to the return to a healthy state
             */
            recovery_time: number | null;
            /** Subsystem */
            subsystem: string;
        };
        /** ReportArtifact */
        ReportArtifact: {
            /** Content Type */
            content_type: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name: string;
            /** Sha256 */
            sha256?: string | null;
            /** Size Bytes */
            size_bytes: number;
            /** Storage Key */
            storage_key: string;
        };
        /** ReportRun */
        ReportRun: {
            /** Ended At */
            ended_at: string | null;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Seed */
            seed: number;
            /** Simulation Duration */
            simulation_duration: number;
            /** Speed */
            speed: number;
            /** Started At */
            started_at: string | null;
            state: components["schemas"]["RunState"];
        };
        /** ReportScenario */
        ReportScenario: {
            /** Api Version */
            api_version: string;
            /** Assertion Count */
            assertion_count: number;
            /** Content Hash */
            content_hash: string;
            /** Description */
            description: string;
            /**
             * Document
             * @description Canonical YAML of the executed scenario
             */
            document: string;
            /** Event Count */
            event_count: number;
            /** Mission Timeout */
            mission_timeout: string;
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /**
         * ReportSummary
         * @description Headline figures generated from observed events (never hard-coded).
         */
        ReportSummary: {
            /** Affected Domains */
            affected_domains: number;
            /** Critical Failures */
            critical_failures: number;
            /** Degraded Transitions */
            degraded_transitions: number;
            /** Fault Containment */
            fault_containment: string;
            /** Faults Applied */
            faults_applied: number;
            /** Faults Injected */
            faults_injected: number;
            /** Loss Of Control */
            loss_of_control: boolean;
            /** Mean Time To Recovery */
            mean_time_to_recovery: number | null;
            /** Mission Complete */
            mission_complete: boolean;
            /** Recovered Subsystems */
            recovered_subsystems: number;
            /** Safety Preservation */
            safety_preservation: string;
        };
        /** ReportTarget */
        ReportTarget: {
            /** Adapter */
            adapter: string;
            /** Adapter Version */
            adapter_version: string | null;
            /** Configuration */
            configuration: {
                [key: string]: string | number | boolean;
            };
            /** Data Origin */
            data_origin: string;
            /** Topology Id */
            topology_id: string;
            /** Vehicle */
            vehicle: string;
        };
        /** ResilienceReport */
        ResilienceReport: {
            /**
             * Actual Path
             * @description Downsampled trajectory
             */
            actual_path: components["schemas"]["PathPoint"][];
            /** Artifacts */
            artifacts: components["schemas"]["ReportArtifact"][];
            /** Assertions */
            assertions: components["schemas"]["AssertionResult"][];
            /** Events */
            events: components["schemas"]["RunEvent"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            hard_gate_result: components["schemas"]["BenchmarkResult"];
            metrics: components["schemas"]["MetricsResult"];
            planned_path: components["schemas"]["PlannedPath"] | null;
            provenance: components["schemas"]["Provenance"];
            /** Resilience Score */
            resilience_score: number;
            result: components["schemas"]["BenchmarkResult"];
            run: components["schemas"]["ReportRun"];
            /** Run Id */
            run_id: string;
            scenario: components["schemas"]["ReportScenario"];
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            score: components["schemas"]["ScoreResult"];
            /** Subsystem Timeline */
            subsystem_timeline: components["schemas"]["ComponentStateInterval"][];
            summary: components["schemas"]["ReportSummary"];
            target: components["schemas"]["ReportTarget"];
            topology: components["schemas"]["SystemTopology"];
        };
        /** RunCreateRequest */
        RunCreateRequest: {
            /** Adapter */
            adapter?: ("mock" | "px4-gazebo" | "replay") | null;
            /** Document */
            document?: string | null;
            /**
             * Label
             * @default
             */
            label: string;
            /** Replay Source Run Id */
            replay_source_run_id?: string | null;
            /** Scenario Name */
            scenario_name?: string | null;
            /** Seed */
            seed?: number | null;
            /** Speed */
            speed?: number | null;
        };
        /** RunDetail */
        RunDetail: {
            /** Adapter */
            adapter: string;
            /** Artifacts */
            artifacts: components["schemas"]["ArtifactOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Event Count */
            event_count: number;
            hard_gate_result: components["schemas"]["BenchmarkResult"] | null;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Last Simulation Time */
            last_simulation_time: number;
            /** Mission Complete */
            mission_complete: boolean;
            planned_path: components["schemas"]["PlannedPath"] | null;
            /** Provenance */
            provenance: {
                [key: string]: unknown;
            };
            /** Reason */
            reason: string;
            /** Replay Source Run Id */
            replay_source_run_id?: string | null;
            /** Report Available */
            report_available: boolean;
            /** Resilience Score */
            resilience_score: number | null;
            result: components["schemas"]["BenchmarkResult"] | null;
            /** Runner Id */
            runner_id: string | null;
            /** Sample Count */
            sample_count: number;
            /** Scenario Document */
            scenario_document: string;
            /** Scenario Hash */
            scenario_hash: string;
            /** Scenario Name */
            scenario_name: string;
            /** Scenario Version */
            scenario_version: string;
            /** Seed */
            seed: number;
            /** Speed */
            speed: number;
            /** Started At */
            started_at: string | null;
            state: components["schemas"]["RunState"];
            summary: components["schemas"]["ReportSummary"] | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Vehicle */
            vehicle: string;
        };
        /**
         * RunEvent
         * @description A discrete, classified event that happened during a run.
         */
        RunEvent: {
            /**
             * Event Type
             * @description Machine readable type, snake_case
             */
            event_type: string;
            kind: components["schemas"]["EventKind"];
            /** Message */
            message: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Run Id */
            run_id: string;
            /**
             * Scenario Event Id
             * @description Scenario event this run event originates from
             */
            scenario_event_id?: string | null;
            /**
             * Sequence
             * @description Monotonic sequence number within the run
             */
            sequence: number;
            /** @default info */
            severity: components["schemas"]["Severity"];
            /** Simulation Time */
            simulation_time: number;
            source: components["schemas"]["EventSource"];
            state_after?: components["schemas"]["ComponentState"] | null;
            state_before?: components["schemas"]["ComponentState"] | null;
            /** Subsystem */
            subsystem?: string | null;
            /**
             * Wall Time
             * Format: date-time
             */
            wall_time?: string;
        };
        /**
         * RunFinishedMessage
         * @description Final word of the runner: the run is over and no more messages will follow.
         */
        RunFinishedMessage: {
            /**
             * Event Count
             * @default 0
             */
            event_count: number;
            /** Final Component States */
            final_component_states?: {
                [key: string]: string;
            };
            /**
             * Mission Complete
             * @default false
             */
            mission_complete: boolean;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "completed" | "failed" | "cancelled";
            /**
             * Protocol Version
             * @default 1
             */
            protocol_version: string;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Run Id */
            run_id: string;
            /** Runner Id */
            runner_id: string;
            /**
             * Sample Count
             * @default 0
             */
            sample_count: number;
            /**
             * Sent At
             * Format: date-time
             */
            sent_at?: string;
            /**
             * Simulation Time
             * @default 0
             */
            simulation_time: number;
            /**
             * Type
             * @default run_finished
             * @constant
             */
            type: "run_finished";
        };
        /** RunListResponse */
        RunListResponse: {
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Runs */
            runs: components["schemas"]["RunSummary"][];
            /** Total */
            total: number;
        };
        /** RunnerOut */
        RunnerOut: {
            /** Active Run Id */
            active_run_id: string | null;
            /** Adapters */
            adapters: string[];
            /**
             * Last Heartbeat At
             * Format: date-time
             */
            last_heartbeat_at: string;
            /** Online */
            online: boolean;
            /** Runner Id */
            runner_id: string;
            /** Version */
            version: string;
        };
        /**
         * RunState
         * @enum {string}
         */
        RunState: "CREATED" | "VALIDATING" | "QUEUED" | "PREPARING" | "RUNNING" | "RECOVERING" | "COLLECTING" | "ANALYZING" | "COMPLETED" | "FAILED" | "CANCELLED";
        /** RunSummary */
        RunSummary: {
            /** Adapter */
            adapter: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Event Count */
            event_count: number;
            hard_gate_result: components["schemas"]["BenchmarkResult"] | null;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Last Simulation Time */
            last_simulation_time: number;
            /** Mission Complete */
            mission_complete: boolean;
            /** Reason */
            reason: string;
            /** Replay Source Run Id */
            replay_source_run_id?: string | null;
            /** Resilience Score */
            resilience_score: number | null;
            result: components["schemas"]["BenchmarkResult"] | null;
            /** Runner Id */
            runner_id: string | null;
            /** Sample Count */
            sample_count: number;
            /** Scenario Hash */
            scenario_hash: string;
            /** Scenario Name */
            scenario_name: string;
            /** Scenario Version */
            scenario_version: string;
            /** Seed */
            seed: number;
            /** Speed */
            speed: number;
            /** Started At */
            started_at: string | null;
            state: components["schemas"]["RunState"];
            summary: components["schemas"]["ReportSummary"] | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Vehicle */
            vehicle: string;
        };
        /** SafetyMetrics */
        SafetyMetrics: {
            /** Control Availability */
            control_availability: number;
            /**
             * Flight Control Available
             * @description Flight core never left a healthy state
             */
            flight_control_available: boolean;
            /** Loss Of Control */
            loss_of_control: boolean;
            /**
             * Preserved
             * @description No loss of control and flight core always available
             */
            preserved: boolean;
            /** Safe State Reached */
            safe_state_reached: boolean;
        };
        /** ScenarioCreateRequest */
        ScenarioCreateRequest: {
            /** Document */
            document: string;
            /**
             * Overwrite
             * @default false
             */
            overwrite: boolean;
        };
        /** ScenarioDetail */
        ScenarioDetail: {
            /** Adapter */
            adapter: string;
            /** Assertion Count */
            assertion_count: number;
            /** Content Hash */
            content_hash: string;
            /** Description */
            description: string;
            /** Document */
            document: string;
            /** Event Count */
            event_count: number;
            /** Expanded Events */
            expanded_events: {
                [key: string]: unknown;
            }[];
            last_run?: components["schemas"]["RunSummary"] | null;
            /** Name */
            name: string;
            /**
             * Scenario
             * @description Parsed scenario (canonical JSON)
             */
            scenario: {
                [key: string]: unknown;
            };
            /** Source */
            source: string;
            /** Tags */
            tags: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: string;
            /** Warnings */
            warnings: components["schemas"]["ValidationIssue"][];
        };
        /** ScenarioSummary */
        ScenarioSummary: {
            /** Adapter */
            adapter: string;
            /** Assertion Count */
            assertion_count: number;
            /** Content Hash */
            content_hash: string;
            /** Description */
            description: string;
            /** Event Count */
            event_count: number;
            last_run?: components["schemas"]["RunSummary"] | null;
            /** Name */
            name: string;
            /** Source */
            source: string;
            /** Tags */
            tags: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: string;
        };
        /** ScenarioValidateRequest */
        ScenarioValidateRequest: {
            /** Document */
            document: string;
        };
        /** ScenarioValidateResponse */
        ScenarioValidateResponse: {
            /** Canonical Yaml */
            canonical_yaml?: string | null;
            /** Content Hash */
            content_hash?: string | null;
            /** Expanded Events */
            expanded_events?: {
                [key: string]: unknown;
            }[];
            /** Issues */
            issues: components["schemas"]["ValidationIssue"][];
            /** Scenario */
            scenario?: {
                [key: string]: unknown;
            } | null;
            /** Valid */
            valid: boolean;
            /** Warnings */
            warnings: components["schemas"]["ValidationIssue"][];
        };
        /** ScoreParameters */
        ScoreParameters: {
            /**
             * Containment Penalty Per Domain
             * @default 0.25
             */
            containment_penalty_per_domain: number;
            /**
             * Mttr Limit
             * @description Recovery time scoring 0.0 (s)
             * @default 30
             */
            mttr_limit: number;
            /**
             * Mttr Target
             * @description Recovery time scoring 1.0 (s)
             * @default 5
             */
            mttr_target: number;
        };
        /** ScoreProfile */
        ScoreProfile: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name: string;
            parameters?: components["schemas"]["ScoreParameters"];
            /**
             * Weights
             * @description Dimension weights, must sum to 100
             */
            weights: {
                [key: string]: number;
            };
        };
        /** ScoreResult */
        ScoreResult: {
            /** Dimensions */
            dimensions: components["schemas"]["DimensionScore"][];
            hard_gate_result: components["schemas"]["BenchmarkResult"];
            /** Hard Gates */
            hard_gates: components["schemas"]["HardGate"][];
            profile: components["schemas"]["ScoreProfile"];
            /** Reason */
            reason: string;
            result: components["schemas"]["BenchmarkResult"];
            /** Total */
            total: number;
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "info" | "low" | "medium" | "high" | "critical";
        /** StreamCompleted */
        StreamCompleted: {
            /** Report Available */
            report_available: boolean;
            run: components["schemas"]["RunSummary"];
            /**
             * Type
             * @default completed
             * @constant
             */
            type: "completed";
        };
        /** StreamHeartbeat */
        StreamHeartbeat: {
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
            /**
             * Type
             * @default heartbeat
             * @constant
             */
            type: "heartbeat";
        };
        /** StreamSnapshot */
        StreamSnapshot: {
            /** Events */
            events: components["schemas"]["RunEvent"][];
            run: components["schemas"]["RunDetail"];
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
            /** Telemetry */
            telemetry: components["schemas"]["TelemetrySample"][];
            /**
             * Type
             * @default snapshot
             * @constant
             */
            type: "snapshot";
        };
        /** SystemInfo */
        SystemInfo: {
            /** Adapters */
            adapters: components["schemas"]["AdapterOut"][];
            /** Catalog */
            catalog: components["schemas"]["CatalogEntryOut"][];
            /** Component States */
            component_states: components["schemas"]["ComponentState"][];
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Effects */
            effects: components["schemas"]["EffectDescriptor"][];
            /** Environment */
            environment: string;
            /** Git Commit */
            git_commit: string | null;
            health: components["schemas"]["ComponentHealth"];
            /** Protocol Version */
            protocol_version: string;
            /** Report Schema Version */
            report_schema_version: string;
            /** Run States */
            run_states: components["schemas"]["RunState"][];
            /** Runners */
            runners: components["schemas"]["RunnerOut"][];
            /** Scenario Api Version */
            scenario_api_version: string;
            /** Score Profiles */
            score_profiles: components["schemas"]["ScoreProfile"][];
            /** Software Version */
            software_version: string;
            topology: components["schemas"]["SystemTopology"];
        };
        /** SystemTopology */
        SystemTopology: {
            /** Components */
            components: components["schemas"]["Component"][];
            /** Dependencies */
            dependencies: components["schemas"]["Dependency"][];
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Trust Boundaries */
            trust_boundaries: components["schemas"]["TrustBoundary"][];
            /** Vehicle Class */
            vehicle_class: string;
        };
        /**
         * TelemetryMessage
         * @description A batch of telemetry samples, ordered by simulation time.
         */
        TelemetryMessage: {
            /**
             * Protocol Version
             * @default 1
             */
            protocol_version: string;
            /** Run Id */
            run_id: string;
            /** Samples */
            samples: components["schemas"]["TelemetrySample"][];
            /**
             * Sent At
             * Format: date-time
             */
            sent_at?: string;
            /**
             * Sequence
             * @description Batch sequence number
             */
            sequence: number;
            /**
             * Type
             * @default telemetry
             * @constant
             */
            type: "telemetry";
        };
        /** TelemetryResponse */
        TelemetryResponse: {
            /** Complete */
            complete: boolean;
            /** Count */
            count: number;
            /** Run Id */
            run_id: string;
            /** Samples */
            samples: components["schemas"]["TelemetrySample"][];
            /** Stride */
            stride: number;
            /** Total */
            total: number;
        };
        /**
         * TelemetrySample
         * @description One normalized telemetry sample at a simulation instant.
         */
        TelemetrySample: {
            attitude: components["schemas"]["Attitude"];
            communications: components["schemas"]["CommunicationsStatus"];
            flight: components["schemas"]["FlightStatus"];
            geo?: components["schemas"]["GeoPosition"] | null;
            /**
             * Health
             * @description Component states keyed by subsystem id
             */
            health?: {
                [key: string]: components["schemas"]["ComponentState"];
            };
            mission: components["schemas"]["MissionStatus"];
            navigation: components["schemas"]["NavigationStatus"];
            position: components["schemas"]["Position"];
            power: components["schemas"]["PowerStatus"];
            /**
             * Source
             * @description Adapter that produced the sample (mock, px4-gazebo, replay)
             */
            source: string;
            /**
             * T
             * @description Simulation time (s)
             */
            t: number;
            velocity: components["schemas"]["Velocity"];
            /**
             * Wall Time
             * Format: date-time
             */
            wall_time?: string;
        };
        /** TrustBoundary */
        TrustBoundary: {
            /**
             * Description
             * @default
             */
            description: string;
            downstream_zone: components["schemas"]["TrustZone"];
            /**
             * Enforcement Point
             * @description Component id acting as policy enforcement point
             */
            enforcement_point?: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            upstream_zone: components["schemas"]["TrustZone"];
        };
        /**
         * TrustZone
         * @description Trust zones, ordered from least to most trusted.
         * @enum {string}
         */
        TrustZone: "external" | "mission" | "flight_critical";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationIssue */
        ValidationIssue: {
            /**
             * Code
             * @default invalid
             */
            code: string;
            /** Message */
            message: string;
            /**
             * Path
             * @description Location in the scenario document, e.g. 'events[2].inject'
             */
            path: string;
            /**
             * Severity
             * @default error
             */
            severity: string;
        };
        /** Velocity */
        Velocity: {
            /**
             * Vx
             * @description East velocity (m/s)
             */
            vx: number;
            /**
             * Vy
             * @description North velocity (m/s)
             */
            vy: number;
            /**
             * Vz
             * @description Up velocity (m/s)
             */
            vz: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    compare_api_v1_compare_get: {
        parameters: {
            query: {
                /** @description Baseline run id */
                baseline: string;
                /** @description Candidate run id */
                candidate: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: {
                adapter?: string | null;
                limit?: number;
                offset?: number;
                result?: string | null;
                scenario?: string | null;
                state?: components["schemas"]["RunState"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    artifacts_api_v1_runs__run_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    artifact_api_v1_runs__run_id__artifacts__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Artifact content with its stored media type */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Invalid artifact name */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Run or artifact not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_v1_runs__run_id__events_get: {
        parameters: {
            query?: {
                after_sequence?: number;
                kind?: string[] | null;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_api_v1_runs__run_id__metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recording_api_v1_runs__run_id__recording_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recording document served as an attachment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingOut"];
                };
            };
            /** @description Run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_api_v1_runs__run_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The stored report.json artifact, byte for byte */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResilienceReport"];
                };
            };
            /** @description Run not found or not analyzed yet */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_html_api_v1_runs__run_id__report_html_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Self-contained HTML report (inline styles only, no scripts) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Run not found or not analyzed yet */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    telemetry_api_v1_runs__run_id__telemetry_get: {
        parameters: {
            query?: {
                /** @description Return every sample (bounded by a hard cap) */
                all?: boolean;
                from?: number | null;
                limit?: number | null;
                to?: number | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenarios_api_v1_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioSummary"][];
                };
            };
        };
    };
    create_scenario_api_v1_scenarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenario_api_v1_scenarios__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scenario_api_v1_scenarios__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenario_document_api_v1_scenarios__name__document_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_scenario_api_v1_scenarios_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_info_api_v1_system_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfo"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
